### PR TITLE
[fix #18] Java agent read-only flow view fix

### LINKED ISSUE #18: [bug] Java agent read-only flow view is broken

### PR DESCRIPTION
**Pull request by martinzink**
#18

### CODE REVIEW

File: website/src/services/index.d.ts [hunk 1]
```diff
@@ -41,6 +41,32 @@ interface FlowInfo {
...
+  flowId: Uuid,
+  queues: {[id: Uuid]: {
+      dataSize: number,
+      dataSizeMax: number,
+      size: number,
+      sizeMax: number,
+      sizeUtilization: number,
+      dataSizeUtilization: number
+  }},
+  processorStatuses: {[index: number]:{
```
Comment (adamdebreceni) [inline website/src/services/index.d.ts:54]: instead of `{[index:number]: T}` it could be `T[]` to type an `array of T`

**Review by adamdebreceni — APPROVED** [review]
